name = "10massage"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

# 正確指定Pages的構建輸出目錄
pages_build_output_dir = ".next/standalone"

# D1數據庫配置
[[d1_databases]]
binding = "DB"
database_name = "10massage-db"
database_id = "d4bee1b5-2b48-4355-af90-0214c5162981"

# R2存儲桶配置
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "10massage-storage" 